version: "3"

networks:
  coho_network:

services:

  nginx:
    container_name: COHO_nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/var/www/html
      - ./logs:/var/log
    env_file:
      - .env
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php-fpm
      - mariaDB
    networks:
      - coho_network
    restart: always


  mariaDB:
    container_name: COHO_mariaDB
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql:rw
    networks:
      - coho_network


  php-fpm:
    container_name: COHO_php-fpm
    env_file:
      - .env
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    build:
      context: ./docker/php-fpm/
      args:
        - PHP_VERSION=${PHP_VERSION}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./webapp:/var/www/html
    networks:
      - coho_network
    restart: always


  adminer:
    container_name: COHO_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - nginx
    networks:
      - coho_network



